### ISSUE TITLE
Loaded SAM_hq_vit_h后标注报错RuntimeError: "upsample_bilinear2d_out_frame" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by DrMio** [yatengLG/ISAT_with_segment_anything#126]

**Comment by DrMio** [comment]
Traceback (most recent call last):
  File \ISAT\widgets\canvas.py", line 430, in mousePressEvent
    self.update_mask()
  File "\ISAT\widgets\canvas.py", line 522, in update_mask
    masks = self.mainwindow.segany.predict_with_point_prompt(self.click_points, self.click_points_mode)
  File "\ISAT_with_segment_anything\ISAT_with_segment_anything-master\ISAT\segment_any\segment_any.py", line 94, in predict_with_point_pro
mpt
    masks, scores, logits = self.predictor_with_point_prompt.predict(
  File "\ISAT_with_segment_anything\ISAT_with_segment_anything-master\ISAT\segment_anything_hq\predictor.py", line 157, in predict        
    masks, iou_predictions, low_res_masks = self.predict_torch(
    return func(*args, **kwargs)
  File "\ISAT_with_segment_anything-master\ISAT\segment_anything_hq\predictor.py", line 246, in predict_torch  
    masks = self.model.postprocess_masks(low_res_masks, self.input_size, self.original_size)
  File "\ISAT_with_segment_anything\ISAT_with_segment_anything-master\ISAT\segment_anything_hq\modeling\sam.py", line 157, in postprocess_
masks
    masks = F.interpolate(
  File "\anaconda3\envs\isat_env\lib\site-packages\torch\nn\functional.py", line 3959, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: "upsample_bilinear2d_out_frame" not implemented for 'BFloat16'

**Comment by yatengLG** [comment]
你更新下代码，或者升级下torch版本吧。

要是其他模型也不能运行，就是你环境问题。
这边ubuntu以及windows下都是测试没问题的。

**Comment by yatengLG** [comment]
大概率是因为你torch版本低了，升到2.1.1及以上即可

**Comment by DrMio** [comment]
您好，是的，Torch更新2.1.2后问题解决了！感谢！
