### ISSUE TITLE
请问如何打包为exe 

### ISSUE THREAD

**Issue by happybear1015** [yatengLG/ISAT_with_segment_anything#37]

**Comment by yatengLG** [comment]
功能还在添加中，没有提供打包好的exe包

如果你有需求，可以通过pyinstaller来打包生成exe，建议添加-D参数，打包为文件夹。

**Comment by happybear1015** [comment]
添加了-D 生成的exe没启动不了

**Comment by yatengLG** [comment]
你可以添加-W，在打包好运行时，看下命令行报什么错

**Comment by happybear1015** [comment]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "widgets\mainwindow.py", line 56, in __init__
  File "widgets\mainwindow.py", line 172, in reload_cfg
  File "configs.py", line 9, in load_config
FileNotFoundError: [Errno 2] No such file or directory: 'default.yaml'

**Comment by happybear1015** [comment]
> 你可以添加-W，在打包好运行时，看下命令行报什么错

Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "widgets\mainwindow.py", line 56, in __init__
  File "widgets\mainwindow.py", line 172, in reload_cfg
  File "configs.py", line 9, in load_config
FileNotFoundError: [Errno 2] No such file or directory: 'default.yaml'

**Comment by happybear1015** [comment]
已经解决啦，谢谢！根据提示缺什么，添加什么。
